### PR TITLE
Mark initial service health check as passing

### PR DESCRIPTION
**Pull request by franek1709**

### CODE REVIEW

**Comment by janisz** [comment]
> 2 weeks to analyse, 1 line to fix. This is how we roll in infra tools.
@pbetkier Please share the story... in commit description.

**Comment by pierresouchay** [comment]
We went thru same issues with our own registration system, even if we did choose to keep failing by default behavior.
Note that you might choose Warning instead of Passing to avoid load-balancing too aggressively your instances (since warning allows to have a specific Weight in Consul 1.0.7+)

**Comment by franek1709** [comment]
> We went thru same issues with our own registration system, even if we did choose to keep failing by default behavior.
> Note that you might choose Warning instead of Passing to avoid load-balancing too aggressively your instances (since warning allows to have a specific Weight in Consul 1.0.7+)

I'm not convinced if we should replace passing status with warning. In my opinion passing status is more logical in this case. This healthcheck was checked a second ago by marathon. We know it passed. It's a matter of internal consul implementation it will be checked again for few seconds. Moreover we are likely to encounter additional problems if we do this. As I found in [consul docs](https://www.consul.io/docs/agent/services.html#dns-srv-weights):

 > Services with warning checks are included in responses by default, but excluded if the optional param 
 only_passing = true is present in agent DNS configuration or ?passing is used via the API.

If we mark these initial healthchecks with warning status their services will not be returned in API queries with ?passing parameter. In our case this will make these services effectively unhealthy - we use api calls we ?passing parameter in few places in our code.

**Comment by pierresouchay** [comment]
Hello @franek1709,

I am just saying that being able to configure initial state for checks is a nice feature (I mean, choosing between passing/warning/critical). This allows to choose between initial status (and warning might make sense).

Regarding the ?passing parameter, this is just a way of doing it, on our side, we are filtering the nodes returned (and not using ?passing), same for DNS.

warning allows for instance to have less weight during load balancing, I explain here how we did our load-balancer and how we are using warning for instance: https://medium.com/criteo-labs/discovery-with-consul-at-scale-1d6808202d86

My point is: being able to configure the initial state would be a useful thing to provide IMHO

**Comment by franek1709** [comment]
> Hello @franek1709,
> 
> I am just saying that being able to configure initial state for checks is a nice feature (I mean, choosing between passing/warning/critical). This allows to choose between initial status (and warning might make sense).
> 
> Regarding the ?passing parameter, this is just a way of doing it, on our side, we are filtering the nodes returned (and not using ?passing), same for DNS.
> 
> warning allows for instance to have less weight during load balancing, I explain here how we did our load-balancer and how we are using warning for instance: https://medium.com/criteo-labs/discovery-with-consul-at-scale-1d6808202d86
> 
> My point is: being able to configure the initial state would be a useful thing to provide IMHO

I agree. Ability to configure this state can be a nice feature. I will add this option to this PR.

**Pull request merged**
