### PR TITLE
Release 0.9.1

### PR DESCRIPTION
**Pull request by AlfredBroda**

### CODE REVIEW

**Comment by AlfredBroda** [comment]
Removed the offending premature tag.

**Comment by medzin** [comment]
Change `Post release version cleanup` commit message to `Change version to dev-master` or something similar.

**Comment by medzin** [comment]
Did you prepared release notes also?

**Comment by AlfredBroda** [comment]
Will do the message change if you don't like this one... I'm still in the process of collecting those - would love to have this done by GitHub though.

**Comment by medzin** [comment]
Automatic building of a changelog will be as good as our commit history and I would not like to limit how features are merged into the master - multiple pull requests with the same feature would end with many entries in the changelog which you have to summarize manually anyway.

**Pull request merged**
